# Generated by Django 2.0.5 on 2018-08-13 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_auto_20180809_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='125b44158ba34a28a6b98cb953c58b3b', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postchat',
            name='uuid',
            field=models.CharField(default='0345e8c07d654740a2fef2174f0c05d1', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postchatphoto',
            name='post_chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.PostChat'),
        ),
        migrations.AlterField(
            model_name='postchattext',
            name='post_chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.PostChat'),
        ),
        migrations.AddField(
            model_name='postcommentcount',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.Post'),
        ),
    ]
