# Generated by Django 2.0.5 on 2018-08-19 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object', '0005_auto_20180817_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostChatRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='a7b2a17973d3447c9e25fad8d0c26707', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postchat',
            name='uuid',
            field=models.CharField(default='3015fe6e46aa4646bdf978c27863d3c5', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='uuid',
            field=models.CharField(default='5f0b2b30c7e144c6aceb725cf5e43319', max_length=34, unique=True),
        ),
        migrations.AddField(
            model_name='postchatread',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.Post'),
        ),
        migrations.AddField(
            model_name='postchatread',
            name='post_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.PostChat'),
        ),
        migrations.AddField(
            model_name='postchatread',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postchatread',
            unique_together={('user', 'post_chat')},
        ),
    ]
