# Generated by Django 2.0.5 on 2018-08-27 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('object', '0008_auto_20180826_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postchatrestmessagecount',
            old_name='post',
            new_name='post_chat',
        ),
        migrations.AddField(
            model_name='postchatrestmessagelike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default='a75aa21bb6984316aa9078f969b6ad05', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postchat',
            name='uuid',
            field=models.CharField(default='b8056bd6de1341fb952ed3a231fcd6a7', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postchatrestmessage',
            name='uuid',
            field=models.CharField(default='77c1cd6edc6e46199369686aa32342ce', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='uuid',
            field=models.CharField(default='5f65579396e3431d82116bdcbf5f06c0', max_length=34, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='postchatlike',
            unique_together={('user', 'post_chat')},
        ),
        migrations.RemoveField(
            model_name='postchatrestmessagelike',
            name='count',
        ),
        migrations.AlterUniqueTogether(
            name='postchatrestmessagelike',
            unique_together={('user', 'post_chat_rest_message')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
    ]
